### ISSUE TITLE
 Is it possible to load more than one Obj file at same time in a SurfaceView?

### ISSUE THREAD

**Issue by braver-tool** [dbrant/ModelViewer3D#17] opened 2021-08-16 14:29 UTC
Is it possible to load more than one Obj file at same time in a SurfaceView?

Sure, right now the model is stored as a global field in `ModelViewerApplication.java`. You can change this to be a `List` of models, and then render all of them in `ModelRenderer.onDrawFrame()`.

_Originally posted by @dbrant in https://github.com/dbrant/ModelViewer3D/issues/7#issuecomment-480032248_

I still not complete this, and also I tried with your updated source for my above question, but it's not working for me, So Could you share code to load more than one object file in the same surface view?

**Comment by dbrant** [comment] 2021-08-17 14:31
If you share your project where you tried to do this yourself, I'll be happy to take a look.

**Comment by braver-tool** [comment] 2021-08-24 12:28
Thanks for your reply.I shared here my sample application, it's based on your code. 
https://github.com/braver-tool/3DViewer

I add one menu named 'load multiple objects', you can click that and see my error.

I added multiple objects as list as you told, can you verify that too?. Since I got human body 3D view like below,
https://github.com/braver-tool/3DViewer/blob/main/actual_anatomy.jpeg

But I actually need like below,
https://github.com/braver-tool/3DViewer/blob/main/error_view.jpeg

I used separate body parts as .obj file because I need to get the body part name when I select the part from the model.

Please give any idea to get correct human anatomy like  from the above code. Thanks in advance.

**Comment by dbrant** [comment] 2021-08-28 19:56
OK, it looks like you're loading the list of models correctly.
The issue is that the app centers all the objects on the same center-of-mass, so all of your objects are being drawn on top of each other. How is the app supposed to know the x,y,z offset of each model?

**Comment by braver-tool** [comment] 2021-09-28 06:38
Sorry for the late reply, as you said, the above issue is every object has x,y,z coordinates from the center of mass. Is it possible to add all child models to one parent model? by the way, we have to set x,y,z coordinates to the parent model as we want, and child models have textureCoords from their obj files.

**Comment by dbrant** [comment] 2021-09-28 14:06
Sure, you can extend the model-loading logic however you like.
This is, however, getting outside of the scope of this app, so I'm closing this issue.

**Closed by dbrant** 2021-09-28 14:06 UTC
